
services:

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    networks:
      lakehouse-net:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./docker/minio/data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      lakehouse-net:
    volumes:
      - ./docker/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      lakehouse-net:
    ports:
      - 19120:19120

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./docker/trino/catalog:/etc/trino/catalog
    networks:
      lakehouse-net:
    depends_on:
      - nessie
      - minio

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./docker/jupyter/work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    networks:
      lakehouse-net:

networks:
  lakehouse-net: